### ISSUE TITLE
#turn validates input correctly test

### ISSUE THREAD

**Issue by fiveinfinity** [learn-co-curriculum/ttt-8-turn#12]
This test seems to be written incorrectly. You're passing it a test as if the #valid_move method is a stand alone method. Its arguments are being used and changed elsewhere, and my other tests can't pass if you're passing it a string.

Lastly, after looking at Learn's solution, would those methods have passed in the previous labs?? It seems like it isn't encouraged to build upon previous labs. 

def display_board(board)
  puts " #{board[0]} | #{board[1]} | #{board[2]} "
  puts "-----------"
  puts " #{board[3]} | #{board[4]} | #{board[5]} "
  puts "-----------"
  puts " #{board[6]} | #{board[7]} | #{board[8]} "
end

def turn(board)
  puts "Please enter 1-9:"
  position = gets.strip
  position = position.to_i

  if(valid_move?(board, position))
    move(board, position, "X")
    display_board(board)
  else
    turn(board)
  end
end

def valid_move?(board, position)
  position = position.to_i
  position = position -= 1

  if position.between?(0, 8) != true
    return false
  elsif board[position] == " " || board[position] == "" || board[position] == nil
    return true
  else
    return false
  end

end

def move(board, position, token)
  position -= 1
  board[position] = token
end

**Comment by AnnJohn** [comment]
reassigning to @mendelB

**Comment by mendelB** [comment]
@fiveinfinity Good point - It looks like the test is indeed specifically requiring the `valid_move?` method to be called with a String of the users input. I think this is OK, as we'd like the String to Integer conversion to occur within the `valid_move?` method to isolate the validation logic there and this seems to be consistent with the previous lab. 
I'm going to go ahead and close this issue. Thanks so much for this submission!
