### ISSUE TITLE
false positive?

### ISSUE THREAD

**Issue by srashid11x** [learn-co-curriculum/ttt-8-turn#13]
def turn(board)
  puts "Please enter 1-9:"
  input = gets.strip
  move(board, input)
  display_board(board)
end

I was able to get all tests to pass with this code.

This repeatedly asks for an input until a valid input is given as desired, but after entering a valid input it calls #display_board as many times as it called #turn printing multiple boards. So if user inputs "a", then "b", then "2", it will ask the user to enter 1-9 until the "2" is entered, but then it will display the new board 3 times.

I changed my code to this to get it working right:

def turn(board)
  puts "Please enter 1-9:"
  input = gets.strip
  if move(board, input)
     display_board(board)
  end
end

**Comment by AnnJohn** [comment]
hi @srashid11x thanks for bringing this up. we'll look into the lab, but were you also able to get help by using the Ask a Question tool in Learn?

**Comment by AnnJohn** [comment]
reassigning to @mendelB

**Comment by mendelB** [comment]
@srashid11x Thanks for this submission.
I believe the actual recursion of the method should be taking place within the `turn` method itself, as placing that in `valid_move?` would be mixing the concerns of the respective methods. However point taken regarding the `display_board` rendering repeatedly, we'll be changing the solution branch code to ensure that problem doesn't occur. Thanks again!
