### ISSUE TITLE
Needs to be reviewed

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ttt-8-turn#2]
:eyes: @SophieDeBenedetto 

Due 9/11/15 EOD

Feel free to make edits in master / solution directly, just make sure to ping me the commits so I can see the diffs. It'd be great, if you are going to make edits in master / solution, especially if they are multiple commits, if you [squashed](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) them locally first before pushing so that I can look at 1 single diff and easily revert or just update with new commits.

**Comment by SophieDeBenedetto** [comment]
reviewed. check out diffs here 689c2090798fc66255938edd899af39a46983df3

**Comment by aviflombaum** [comment]
Thanks those changes are good.

**Comment by aviflombaum** [comment]
@SophieDeBenedetto don't forget to merge master into solution after commits on master.

**Comment by SophieDeBenedetto** [comment]
done, thanks for the reminder.
