### ISSUE TITLE
 Failure/Error: if index.between?(0,8)

### ISSUE THREAD

**Issue by Jimbob2265** [learn-co-curriculum/ttt-8-turn#23]
I keep getting this error and everything works correctly. I even went to the solution and copied and pasted it into my project and got the same error.

![capture](https://cloud.githubusercontent.com/assets/19310938/15454203/30dc8cee-1ff7-11e6-972e-dfb692b96d62.JPG)

**Comment by mennamorato** [comment]
yes we are all running into this issue, highly likely and Rspec problem, i was told by instructor to just move on to next lesson

**Comment by aturkewi** [comment]
@Jimbob2265 and @mennamorato 
Thanks for raising an issue on this :) When I updated the lab I accidentally forgot to have the test return a value when it checked to make sure that `#input_to_index` was called. I just updated this lab to fix it. If you want to get the updated copy, just copy your code to another file. Delete your local repo and your fork, and then just re-fork and re-clone and copy your solution in. (You can also just look at the update and manually make the change as well).

**Comment by Jimbob2265** [comment]
Thanks, I actually manually wrote in the code in for the return of 0 and
got past the lesson. Thanks for fixing though!

Fun Fit Dad
Jim White
WWW.facebook.com/funfitdad
(217)971-4783
