### ISSUE TITLE
ttt-8 rspec issue?

### ISSUE THREAD

**Issue by mennamorato** [learn-co-curriculum/ttt-8-turn#24]
see my question on this - code works fine if i run it normally, checking valid input, checking valid board, asking again if bad user input, etc .  but 'learn' hangs and gets a stack trace fault because of something wrong with rspec script i suspect.   i use recursion for solution of asking again for user input.  others are seeing similar issues i believe.  thanks
![screen shot 2016-05-21 at 11 24 58 pm](https://cloud.githubusercontent.com/assets/1237638/15454395/8baf3a96-1fec-11e6-84df-954a18e21ec1.png)

**Comment by aturkewi** [comment]
@mennamorato  
Thanks for raising an issue on this :) When I updated the lab I accidentally forgot to have the test return a value when it checked to make sure that `#input_to_index` was called. I just updated this lab to fix it. If you want to get the updated copy, just copy your code to another file. Delete your local repo and your fork, and then just re-fork and re-clone and copy your solution in. (You can also just look at the update and manually make the change as well).
