### ISSUE TITLE
RSpec test fails when using recursivity in #turn

### ISSUE THREAD

**Issue by Kamitenshi** [learn-co-curriculum/ttt-8-turn#27]
If we call #turn to get input from users when they enter wrong input, the test fails.
Here's my code 
![turn](https://cloud.githubusercontent.com/assets/14802131/16895291/344efafa-4b72-11e6-8b3a-731f8ac390ba.JPG)

P-S: I am not familiar enough with RSpec to fix it, sorry :/

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by Kamitenshi** [comment]
I just had this issue in this lesson. I think that the problem is in the test run in the RSpec.

I use the Learn IDE. 

Here is the line of the test that fails : 
![rsspec line](https://cloud.githubusercontent.com/assets/14802131/16895909/091ba128-4b84-11e6-8d4c-9198ed9bb670.JPG)

And I also have these information above : (I don't really know what it means)
![unidentified informationjpg](https://cloud.githubusercontent.com/assets/14802131/16895912/1e71a676-4b84-11e6-9aa4-58b8605d6f37.JPG)

But in fact, there are a lot of lines "#./lib/turn.rb:40 in `turn'"  the CLI above this (I could not reach my initial command haha..). So I Imaginethat there is an infinite call of #turn.

I guess it is because of the way the test is built which does not accept the recursivity on #turn because it always provides the same input when #turn is called. Again, I know a little about RSpect, so I let you give the real diagnosis.

I am not sur it was a good idea to implement recursivity there, but I wanted to test another way of doing things, like in the lessons :D

**Comment by pletcher** [comment]
Hi @Kamitenshi, the problem is that `until` block -- that will continue to execute (and increase the size of the call stack) indefinitely, since on any invalid call that position will always be invalid (the position only changes on the next call).

Recursively calling `#turn` is just fine :) If you change the `until` into an `if`-`else` block, I think you'll find that things work pretty well (assuming everything else is in shape) :)
