### ISSUE TITLE
tic tac toe turn logic problem erro mesage No Method Error- any idea how to solve the message

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/ttt-8-turn#29]
![tic tac toe error message no method error](https://cloud.githubusercontent.com/assets/19511967/17831845/16f4754e-66ba-11e6-80bb-ea37ebadb944.png)

**Comment by AnnJohn** [comment]
hi @ICanDoAllThingThroughChrist please use the Ask a Question tool for help. We use this space specifically to raise errors with the actual content of the lessons. Thanks!
