### ISSUE TITLE
Recursion & loops too advanced at this point?

### ISSUE THREAD

**Issue by matbalez** [learn-co-curriculum/ttt-8-turn#3]
It's my sense that recursion is too advanced a concept for the beginner programmer to grasp and use effectively this early on. I feel like they are ready for loops, which are about to come next, but since not covered it's tough to ask them to use either recursion or loops to solve this. 

Feels like this lab should come after basic loops have been covered and we should instruct user to use loops, avoid talk of recursion.

**Comment by aviflombaum** [comment]
Ya, thinking about how to fix this as the next section currently has issues as well.

**Comment by aviflombaum** [comment]
Have re-ordered and addressed this.
