### ISSUE TITLE
passed learn test but the program is not performing like the instructions

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/ttt-8-turn#30]
it is looping through turn(board) method
![turn_looping error](https://cloud.githubusercontent.com/assets/19511967/17832467/2c2e2a36-66c9-11e6-9dde-f7403ad5f10d.png)

**Comment by ICanDoAllThingThroughChrist** [comment]
![turn_looping error2](https://cloud.githubusercontent.com/assets/19511967/17832507/3b708916-66ca-11e6-8107-207ab42826ed.png)

**Comment by AnnJohn** [comment]
hi @ICanDoAllThingThroughChrist could you please use the Ask a Question tool and someone will be available to help you out with your specific problem. Thanks!
