### ISSUE TITLE
Tic Tac Toe Turn missing a file 

### ISSUE THREAD

**Issue by sopharsogood** [learn-co-curriculum/ttt-8-turn#38]
## Link to Canvas

https://learning.flatironschool.com/courses/4537/assignments/126690?module_item_id=262344

## What should be changed?

The lesson says the repository should have a lib/play.rb that comes with helper methods from previous exercises. However, lib/play.rb does not exist in the repository. lib only contains turn.rb, which is blank (since that's where the user is supposed to code).

## Additional context

README.md in the repository has different text from the lesson, and doesn't claim the existence of lib/play.rb

**Comment by sopharsogood** [comment]
The issue seems to be that Tic Tac Toe Turn and the following lesson, Tic Tac Toe Play Loop https://learning.flatironschool.com/courses/4537/assignments/126689?module_item_id=262343 have either their text or their repositories transposed.

**Comment by ihollander** [comment]
Thanks for flagging this issue! It has been resolved so that the lessons on Canvas now show and link to the correct repository.
